repositories:
  excluded_owners:
    - stonecutter-versioning
  disallowed_words:
    - stonecutter
    - template
    - example
entries:
  - id: IMB11/SkinShufflePlugin
    valid: false
  - id: kikugie/multilib
    valid: false
  - id: Qendolin/better-clouds
    curseforge: /EXCLUDED/
  - id: Superkat32/Explosive-Enhancement
    curseforge: /EXCLUDED/
  - id: enjarai/shared-resources
    curseforge: https://www.curseforge.com/minecraft/mc-mods/shared-resources
  - id: RedRain0o0/legacy-skins
    curseforge: https://www.curseforge.com/minecraft/mc-mods/legacy-skins
  - id: Membercat-Studios/ModelShifter
    curseforge: /EXCLUDED/
  - id: anastarawneh/MCCINametagMod
    name: MCC Island Nametag Mod
    curseforge: /EXCLUDED/
  - id: GravityCY/QuickStore
    modrinth: /EXCLUDED/
  - id: enjarai/memories-are-all-we-have
    curseforge: /EXCLUDED/
  - id: IMB11/ExtraShields
    curseforge: https://www.curseforge.com/minecraft/mc-mods/extra-shields
  - id: EmilAhmaBoy/saturative
    curseforge: /EXCLUDED/
  - id: axialeaa/Glissando
    curseforge: /EXCLUDED/
  - id: Overcontrol1/RandomFishing
    curseforge: /EXCLUDED/
  - id: Chailotl/inventory-sort
    name: Chai's Inventory Sorter
    curseforge: /EXCLUDED/
  - id: Mirsario/Minecraft-CameraOverhaul
    name: Camera Overhaul
    curseforge: https://www.curseforge.com/minecraft/mc-mods/cameraoverhaul
  - id: IMB11/MRU
    curseforge: https://www.curseforge.com/minecraft/mc-mods/mru
  - id: sirstotes/Pucks-Parity-Mod
    curseforge: /EXCLUDED/
  - id: sailex428/HudEnhancer
    curseforge: /EXCLUDED/
  - id: BareMinimumStudios/Guilded
    curseforge: /EXCLUDED/
  - id: LopyMine/Fast-Recipe
    curseforge: https://www.curseforge.com/minecraft/mc-mods/fast-recipe
  - id: Vulpeus-Server/kyoyu
    curseforge: /EXCLUDED/
  - id: axialeaa/BlockyBubbles
    curseforge: /EXCLUDED/
  - id: o7Moon/OpenBoatUtils
    curseforge: /EXCLUDED/
  - id: skycatminepokie/autocut
    curseforge: /EXCLUDED/
  - id: Wilyicaro/FactoryAPI
    curseforge: https://www.curseforge.com/minecraft/mc-mods/factory-api
  - id: Kyagara/fred
    curseforge: /EXCLUDED/
  - id: naari3/offers-hud
    curseforge: /EXCLUDED/
  - id: IMB11/Sounds
    curseforge: https://www.curseforge.com/minecraft/mc-mods/sound
  - id: snackbag/TT20
    curseforge: /EXCLUDED/
  - id: kikugie/malilib-extras
    curseforge: /EXCLUDED/
  - id: Anime-pdf/i-cant-do-math
    curseforge: https://www.curseforge.com/minecraft/mc-mods/i-cant-do-math
  - id: enjarai/restart-detector
    curseforge: /EXCLUDED/
  - id: axialeaa/FlorumSporum
    curseforge: /EXCLUDED/
  - id: Chailotl/sushi-bar
    curseforge: /EXCLUDED/
  - id: enjarai/cicada-lib
    name: CICADA
  - id: DuperKnight/DuperAutoWalk
    curseforge: https://www.curseforge.com/minecraft/mc-mods/dupers-autowalk
  - id: Faboslav/it-takes-a-pillage
    curseforge: https://www.curseforge.com/minecraft/mc-mods/it-takes-a-pillage-continuation
  - id: Mat0u5/LifeSeries
    curseforge: /EXCLUDED/
  - id: Lemonnik6484/BetterWalls
    curseforge: https://www.curseforge.com/minecraft/mc-mods/better-walls
  - id: ProunceDev/BetterCooldownsHUD
    modrinth: https://www.curseforge.com/minecraft/mc-mods/bettercooldownshud
  - id: Lemonnik6484/MossMod
    curseforge: /EXCLUDED/
  - id: Kyagara/CoopTweaks
    curseforge: /EXCLUDED/
  - id: btwonion/autodrop
    curseforge: /EXCLUDED/
  - id: Aeldit/CyanSetHome
    curseforge: /EXCLUDED/
  - id: Raik176/datapack-utils
    curseforge: https://www.curseforge.com/minecraft/mc-mods/datapack-utils
  - id: Seggan/deathview
    curseforge: /EXCLUDED/
  - id: Crendgrim/DynamicCrosshairCompat
    curseforge: https://www.curseforge.com/minecraft/mc-mods/dynamic-crosshair-compat
  - id: not-coded/WayFix
    curseforge: /EXCLUDED/
  - id: btwonion/better-boat-movement
    curseforge: /EXCLUDED/
  - id: Raik176/detail-armor-bar-compat
    curseforge: https://www.curseforge.com/minecraft/mc-mods/detailab-compat
  - id: zly2006/x-backup
    curseforge: /EXCLUDED/
  - id: Raik176/mod-credits-reborn
    curseforge: /EXCLUDED/
  - id: sailex428/AI-NPC
    curseforge: /EXCLUDED/
  - id: finnhartshorn/controlify-integrations
    modrinth: /EXCLUDED/
    curseforge: /EXCLUDED/
  - id: plasmoapp/pv-addon-discs
    modrinth: https://modrinth.com/plugin/pv-addon-discs
    curseforge: /EXCLUDED/
  - id: rosebudmods/skin-overrides
    curseforge: /EXCLUDED/
  - id: txnimc/SodiumDynamicLights
    curseforge: https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged
  - id: nobaboy/NobaAddons
    curseforge: /EXCLUDED/
  - id: meza/ServerRedstoneBlock
    curseforge: https://www.curseforge.com/minecraft/mc-mods/server-redstone-block
  - id: celestialfault/toggle-toggle-sprint
    curseforge: /EXCLUDED/
  - id: txnimc/PackAnalytics
    curseforge: https://www.curseforge.com/minecraft/mc-mods/pack-analytics
  - id: isXander/YetAnotherConfigLib
    modrinth: https://www.curseforge.com/minecraft/mc-mods/yacl
  - id: cassiancc/Item-Descriptions
    curseforge: https://www.curseforge.com/minecraft/mc-mods/item-descriptions
  - id: Event-Alerts/EventUtils
    curseforge: /EXCLUDED/
  - id: lvoegl/libanalog-mc
    name: LibAnalog
  - id: lvoegl/analogmovement-mc
    curseforge: https://www.curseforge.com/minecraft/mc-mods/analogmovement
  - id: OmriPH/Penguins
    modrinth: /EXCLUDED/
  - id: txnimc/PronounMC
    curseforge: https://www.curseforge.com/minecraft/mc-mods/pronounmc
  - id: Raik176/rose-gold
    curseforge: /EXCLUDED/
  - id: Bawnorton/DCFixes
    modrinth: /EXCLUDED/
  - id: btwonion/KotlinLangForge
    curseforge: /EXCLUDED/
  - id: meza/DeckedOutOBS
    curseforge: /EXCLUDED/
  - id: Aeldit/CTMSelector
    curseforge: /EXCLUDED/
  - id: MisterCheezeCake/SkyblockTweaks
    curseforge: /EXCLUDED/
  - id: ModLabsCC/ShaderAPI
    curseforge: /EXCLUDED/
  - id: isXander/opti-painting
    curseforge: https://www.curseforge.com/minecraft/mc-mods/optipainting
  - id: imide/ChatHistoryPlus
    curseforge: /EXCLUDED/
  - id: meza/Disable-Christmas-Chests
    curseforge: https://www.curseforge.com/minecraft/mc-mods/disablechristmaschests
  - id: not-coded/codelib
    curseforge: /EXCLUDED/
  - id: Aeldit/Cyan
    curseforge: /EXCLUDED/
  - id: Aeldit/CyanLib
    curseforge: /EXCLUDED/
  - id: txnimc/DoesItTickSC
    name: Does It Tick?
  - id: nvb-uy/Combat-Effects
    curseforge: https://www.curseforge.com/minecraft/mc-mods/combat-effects
  - id: nvb-uy/OffHandTickFix
    name: Off Hand Tick Fix
    modrinth: /EXCLUDED/
    curseforge: https://www.curseforge.com/minecraft/mc-mods/off-hand-tick-fix
  - id: Raik176/better-saved-tabs
    curseforge: https://www.curseforge.com/minecraft/mc-mods/better-saved-tabs
  - id: Raik176/undertale-death-screen
    curseforge: https://www.curseforge.com/minecraft/mc-mods/undertale-death-screen
  - id: txnitxnichopper/PronounMC
    curseforge: https://www.curseforge.com/minecraft/mc-mods/pronounmc
  - id: txnimc/SodiumOptionsModCompat
    curseforge: https://www.curseforge.com/minecraft/mc-mods/sodium-embeddium-options-mod-compat
  - id: pajicadvance/simple-smithing-overhaul
    curseforge: https://www.curseforge.com/minecraft/mc-mods/simple-smithing-overhaul
  - id: pajicadvance/simple-death-improvements
    curseforge: https://www.curseforge.com/minecraft/mc-mods/simple-death-improvements